import type { Metadata } from "next";
import { Libre_Baskerville } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/contexts/ThemeContext";
import "./globals.css";

const libre_baskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
});

// const cormorant_garamond = Cormorant_Garamond({
//   subsets: ["latin"],
//   weight: "600",
// });

export const metadata: Metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body className={`antialiased ${libre_baskerville.className}`}>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
